name: Deploy to Auth0 development account
on:
  push:
    branches: [config/amazon-ses]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install the test dependencies
        run: npm install
      - name: Run tests
        env:
          NODE_ENV: 'test'
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install the auth0-deploy-cli
        run: npm install -g auth0-deploy-cli
      - name: Import changes to the Auth0 staging account
        env:
          AUTH0_CLIENT_SECRET: ${{ secrets.DEV_AUTH0_CLIENT_SECRET }}
          AUTH0_ALLOW_DELETE: true
        run: npm run import:dev
